version: '3.4'

services:
  ignite_instance:
    image: apacheignite/ignite
    ports:
      - "10800:10800"
      - "47100:47100"
      - "47101:47101"

  redis_instance:
    image: redis

  redisfordummies.api:
    image: ${DOCKER_REGISTRY-}redisfordummiesapi
    build:
      context: .
      dockerfile: RedisForDummies.Api/Dockerfile
    depends_on:
      - ignite_instance
      - redis_instance
